version: '3'
services:
  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0315'
      - 'POSTGRES_DB=spring'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080
